version: '3.3'

services:
  database:
    container_name: database
    image: postgres
    environment:
      # Don't do this. This is fine in dev...I guess
      # https://docs.docker.com/engine/swarm/secrets/
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: puttsio
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
